spring.application.name=ECommerce
#Connect to database
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Hibernate Dialect for MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Save logs to file using logback

#Log file path and name
logging.file.name=logs/app.log
logging.level.com.ecommerce=debug
logging.level.root=info